import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.6
blur = true
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 15.0

[keyboard]
bindings = [
  { key = "Backspace", mods = "Command", chars = "\u0015" },
  { key = "Left", mods = "Command", chars = "\u0001" },
  { key = "Right", mods = "Command", chars = "\u0005" },
]
